name = "Assignment"
uuid = "1181494e-2b5f-4cd1-9eb6-aced1908abbf"
version = "0.1.0"
authors = ["ShadowEngineer <ShadowEngineer54@gmail.com>"]

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
Random = "1.11.0"
Revise = "3.13.2"
